repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
        entry: env RUSTFLAGS="-D warnings" cargo check
        args: ['--all']
    -   id: clippy
        args: ['--', '-W', 'clippy::pedantic']
    -   id: cargo-check
        name: cargo-check --features image
        entry: env RUSTFLAGS="-D warnings" cargo check
        args: ['--all', '--features', 'image']
    -   id: clippy
        name: clippy --features image
        args: ['--features', 'image', '--', '-W', 'clippy::pedantic']
    -   id: cargo-check
        name: cargo test --bins
        entry: cargo test
        args: ['--bins']
    -   id: cargo-check
        name: cargo test --tests
        entry: cargo test
        args: ['--tests']
